apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service  # Nombre descriptivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service  # Coherencia en labels
  template:
    metadata:
      labels:
        app: admin-service  # Mismo label
    spec:
      containers:
      - name: university-webapp      
        image: isavb03/admin-service:${BUILD_ID}
        ports:
        - containerPort: 8080        # Puerto del contenedor
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password          