apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - nodePort: 31001
      port: 8081
      targetPort: 8080
  selector:
    app: admin-service          