apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 31001  # Optional: Specify a port (30000-32767)
  selector:
    app: admin-service          